# Importante Spring utiliza la codificacion ISO-8859-1 para leer el applicacion.properties
# Los caracteres de acentos y la ene no estan permitidos

spring.application.name=springexample

# Activa el modo de depuracion de spring (no confundir con logging.level.root), el mismo efecto java -jar myapp.jar ?debug
# debug=true
# o puede habilitarse el modo trace
# trace=true

# Para generar archivos de registro, la ruta puede ser absoluta o relativa al directorio actual
# logging.file.name=registro.log
# logging.file.path=/registro.log (raiz del sistema, en windows c:/) o /var/log (genera archivo spring.log en el directorio)
# crea una carpeta con el nombre del valor, y dentro crea el registro con el nombre spring.log
# Los archivos de registro se rotan al alcanzar los 10MB
# Las configuracion de registro sirven solo si utiliza Logback, el predeterminado de Spring
# logging.logback.rollingpolicy.file-name-pattern El patron de nombre de archivo utilizado para crear archivos de registro.
# logging.logback.rollingpolicy.clean-history-on-start Si la limpieza del archivo de registro debe realizarse al iniciar la aplicacion.
# logging.logback.rollingpolicy.max-file-size El tamano maximo del archivo de registro antes de que se archive.
# logging.logback.rollingpolicy.total-size-cap El tamano maximo que pueden ocupar los archivos de registro antes de ser eliminados.
# logging.logback.rollingpolicy.max-history Numero maximo de archivos de registro de archivo que se conservaran (el valor predeterminado es 7).
# Se puede configurar el log a nivel de paquete
# logging.level.root=warn
# logging.level.org.springframework.web=debug
# logging.level.org.hibernate=error
# Los paquetes se pueden agrupar en un grupo y luego configurarse con una referencia
# logging.group.tomcat=org.apache.catalina,org.apache.coyote,org.apache.tomcat
# logging.level.tomcat=trace

# Registro de informacion de inicio
spring.main.log-startup-info=true

# Habilita o deshabilita la inicializacion diferida de los beans
spring.main.lazy-initialization=false

# Determina si la pancarta (imagen spring boot) debe imprimirse, valores posibles console, log u off
spring.main.banner-mode=log

# Indica cuales perfiles estan activos
# spring.profiles.active=
# Para incluir perfiles activos, estos perfiles se agregan antes que los definidos en spring.profiles.active
# spring.profiles.include[0]=
# spring.profiles.include[1]=
# Definir grupos de perfiles, si defino spring.profiles.active=production, los perfiles proddb y prodmq se activan
# spring.profiles.group.production[0]=proddb
# spring.profiles.group.production[1]=prodmq


# Si se configuran archivos application-{profile}.properties y los perfiles estan activos
# las propiedades de esos archivos de perfil sobreescriben los no especificos. Si se encuentran
# varios perfiles los ultimos prevalecen


# Propiedad creada para probar @Value
app.madera=soita
# Podemos utilizar marcadores de posicion para obtener variables de sistema y JVM, asi como tambien
# propiedades de archivos .properties cargados por Spring, siempre y cuando esten las propiedades
# cargadas antes de ser referenciadas
# Se puede definir un valor por defecto despues de ":"
app.timezone=${user.timezone:Bs.As Argentina}
app.name=${spring.application.name}


# Propiedades para probar @ConfigurationProperties
# Se recomienda que las propiedades esten en kebab case (minusculas y separadas por un guion)
jwt.secret = secret
jwt.issuer = http://localhost:8080
jwt.audience =  http://localhost:8080
jwt.clock-skew = 10000
jwt.valid-for =
jwt.refresh-limit = 1

# Proteger servidor web integrado con ssl
#spring.ssl.bundle.jks.mybundle.key.alias=application
#spring.ssl.bundle.jks.mybundle.keystore.location=classpath:application.p12
#spring.ssl.bundle.jks.mybundle.keystore.password=secret
#spring.ssl.bundle.jks.mybundle.keystore.type=PKCS12